import { Project, Contract, District, Report, AiInsight, SummaryStats } from '../types';

export const mockSummaryStats: SummaryStats = {
  totalBudget: 150000000000, // 150,000,000,000 BDT
  totalSpent: 85000000000,
  activeProjects: 1240,
  delayedProjects: 312,
  highRiskDistricts: 4,
  publicReports: 8450,
};

export const mockDistricts: District[] = [
  { id: 'd1', name: 'Dhaka', riskLevel: 'Medium', riskScore: 65, reportCount: 2100, topSector: 'Roads', suspiciousProjects: 12, trend: 'stable' },
  { id: 'd2', name: 'Chattogram', riskLevel: 'High', riskScore: 82, reportCount: 1850, topSector: 'Housing', suspiciousProjects: 24, trend: 'up' },
  { id: 'd3', name: 'Rajshahi', riskLevel: 'Low', riskScore: 35, reportCount: 420, topSector: 'Education', suspiciousProjects: 3, trend: 'down' },
  { id: 'd4', name: 'Khulna', riskLevel: 'Medium', riskScore: 55, reportCount: 890, topSector: 'Water', suspiciousProjects: 8, trend: 'stable' },
  { id: 'd5', name: 'Sylhet', riskLevel: 'High', riskScore: 78, reportCount: 1200, topSector: 'Health', suspiciousProjects: 18, trend: 'up' },
  { id: 'd6', name: 'Barishal', riskLevel: 'Low', riskScore: 42, reportCount: 310, topSector: 'Local Government', suspiciousProjects: 4, trend: 'down' },
];

export const mockProjects: Project[] = [
  {
    id: 'p1',
    name: 'ঢাকা বাইপাস সড়ক উন্নয়ন',
    district: 'Dhaka',
    sector: 'Roads',
    department: 'Roads and Highways Department',
    budget: 5000000000,
    spent: 4200000000,
    progress: 45,
    deadline: '2026-12-31',
    contractor: 'M/S Rahman Builders',
    status: 'At Risk',
    riskScore: 85,
    complaints: 142,
    description: 'ঢাকা শহরের যানজট নিরসনে বাইপাস সড়ক নির্মাণ প্রকল্প। বাজেটের ৮৪% ব্যয় হলেও কাজের অগ্রগতি মাত্র ৪৫%।',
  },
  {
    id: 'p2',
    name: 'চট্টগ্রাম বন্দর সংযোগ সড়ক',
    district: 'Chattogram',
    sector: 'Roads',
    department: 'Ministry of Shipping',
    budget: 8000000000,
    spent: 2000000000,
    progress: 25,
    deadline: '2025-06-30',
    contractor: 'Karnaphuli Construction Ltd.',
    status: 'Delayed',
    riskScore: 72,
    complaints: 85,
    description: 'চট্টগ্রাম বন্দরের সাথে মূল মহাসড়কের সংযোগ স্থাপন। জমি অধিগ্রহণ জটিলতায় কাজ বিলম্বিত।',
  },
  {
    id: 'p3',
    name: 'রাজশাহী মডেল স্কুল নির্মাণ',
    district: 'Rajshahi',
    sector: 'Education',
    department: 'Ministry of Education',
    budget: 150000000,
    spent: 120000000,
    progress: 85,
    deadline: '2024-12-31',
    contractor: 'Barendra Engineering',
    status: 'On Track',
    riskScore: 20,
    complaints: 5,
    description: 'রাজশাহী শহরে একটি আধুনিক মডেল স্কুল নির্মাণ প্রকল্প। কাজ প্রায় শেষের দিকে।',
  },
  {
    id: 'p4',
    name: 'সিলেট মেডিকেল কলেজ সম্প্রসারণ',
    district: 'Sylhet',
    sector: 'Health',
    department: 'Ministry of Health',
    budget: 3000000000,
    spent: 2800000000,
    progress: 60,
    deadline: '2025-12-31',
    contractor: 'Surma Associates',
    status: 'At Risk',
    riskScore: 88,
    complaints: 210,
    description: 'সিলেট এমএজি ওসমানী মেডিকেল কলেজ হাসপাতালের নতুন ভবন নির্মাণ। নিম্নমানের সামগ্রী ব্যবহারের অভিযোগ রয়েছে।',
  },
  {
    id: 'p5',
    name: 'খুলনা সুপেয় পানি সরবরাহ',
    district: 'Khulna',
    sector: 'Water',
    department: 'WASA',
    budget: 4500000000,
    spent: 4500000000,
    progress: 100,
    deadline: '2024-03-31',
    contractor: 'Rupsha Consortium',
    status: 'Completed',
    riskScore: 15,
    complaints: 22,
    description: 'খুলনা শহরে সুপেয় পানি সরবরাহের জন্য নতুন পাইপলাইন স্থাপন প্রকল্প।',
  },
];

export const mockContracts: Contract[] = [
  {
    id: 'c1',
    projectId: 'p1',
    projectName: 'ঢাকা বাইপাস সড়ক উন্নয়ন',
    contractor: 'M/S Rahman Builders',
    contractAmount: 4800000000,
    startDate: '2022-01-15',
    deadline: '2026-12-31',
    status: 'Active',
    transparencyScore: 45,
    flags: ['Budget Overrun Risk', 'Repeated Contractor'],
  },
  {
    id: 'c2',
    projectId: 'p4',
    projectName: 'সিলেট মেডিকেল কলেজ সম্প্রসারণ',
    contractor: 'Surma Associates',
    contractAmount: 2900000000,
    startDate: '2023-05-10',
    deadline: '2025-12-31',
    status: 'Active',
    transparencyScore: 30,
    flags: ['Limited Competition', 'Low Transparency Score'],
  },
  {
    id: 'c3',
    projectId: 'p3',
    projectName: 'রাজশাহী মডেল স্কুল নির্মাণ',
    contractor: 'Barendra Engineering',
    contractAmount: 145000000,
    startDate: '2023-08-01',
    deadline: '2024-12-31',
    status: 'Active',
    transparencyScore: 92,
    flags: [],
  },
];

export const mockReports: Report[] = [
  {
    id: 'r1',
    district: 'Sylhet',
    sector: 'Health',
    projectName: 'সিলেট মেডিকেল কলেজ সম্প্রসারণ',
    type: 'নিম্নমানের সামগ্রী',
    summary: 'হাসপাতালের নতুন ভবনের পিলারে নিম্নমানের রড ও সিমেন্ট ব্যবহার করা হচ্ছে।',
    date: '2024-05-12',
    status: 'Investigating',
    anonymous: true,
  },
  {
    id: 'r2',
    district: 'Dhaka',
    sector: 'Roads',
    projectName: 'ঢাকা বাইপাস সড়ক উন্নয়ন',
    type: 'কাজে ধীরগতি',
    summary: 'গত ৬ মাস ধরে রাস্তায় কোনো কাজ হচ্ছে না, কিন্তু বিল তোলা হয়েছে।',
    date: '2024-05-10',
    status: 'Pending',
    anonymous: true,
  },
  {
    id: 'r3',
    district: 'Chattogram',
    sector: 'Roads',
    projectName: 'চট্টগ্রাম বন্দর সংযোগ সড়ক',
    type: 'জমি অধিগ্রহণে দুর্নীতি',
    summary: 'ক্ষতিপূরণের টাকা প্রকৃত মালিকদের না দিয়ে ভুয়া কাগজপত্রে তোলা হচ্ছে।',
    date: '2024-05-08',
    status: 'Resolved',
    anonymous: false,
  },
];

export const mockAiInsights: AiInsight[] = [
  {
    id: 'ai1',
    title: 'অস্বাভাবিক ব্যয় ও ধীরগতি',
    district: 'Dhaka',
    severity: 'High',
    confidence: 94,
    explanation: 'ঢাকা বাইপাস সড়ক উন্নয়ন প্রকল্পে বাজেটের ৮৪% ব্যয় হয়েছে, কিন্তু কাজের অগ্রগতি মাত্র ৪৫%। এটি একটি গুরুতর অসঙ্গতি।',
    relatedProjectId: 'p1',
  },
  {
    id: 'ai2',
    title: 'একই ঠিকাদারের আধিপত্য',
    district: 'Sylhet',
    severity: 'Medium',
    confidence: 88,
    explanation: 'Surma Associates গত ২ বছরে সিলেট জেলায় ৫টি বড় স্বাস্থ্য খাতের টেন্ডার পেয়েছে, যেখানে অন্য কোনো প্রতিযোগী ছিল না।',
    relatedProjectId: 'p4',
  },
  {
    id: 'ai3',
    title: 'অভিযোগের আকস্মিক বৃদ্ধি',
    district: 'Chattogram',
    severity: 'High',
    confidence: 91,
    explanation: 'গত ১ মাসে চট্টগ্রাম জেলায় ভূমি অধিগ্রহণ সংক্রান্ত অভিযোগ ৩০০% বৃদ্ধি পেয়েছে।',
  },
];

export const chartData = {
  budgetVsSpending: [
    { name: 'Roads', budget: 500, spent: 320 },
    { name: 'Education', budget: 300, spent: 210 },
    { name: 'Health', budget: 400, spent: 380 },
    { name: 'Water', budget: 200, spent: 150 },
    { name: 'Housing', budget: 350, spent: 180 },
  ],
  reportTrends: [
    { month: 'Jan', reports: 400 },
    { month: 'Feb', reports: 450 },
    { month: 'Mar', reports: 600 },
    { month: 'Apr', reports: 850 },
    { month: 'May', reports: 1200 },
  ],
  projectStatus: [
    { name: 'On Track', value: 650, color: '#10b981' },
    { name: 'Delayed', value: 312, color: '#f59e0b' },
    { name: 'At Risk', value: 128, color: '#ef4444' },
    { name: 'Completed', value: 150, color: '#3b82f6' },
  ]
};
